//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTAPI.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.Videos = new HashSet<Video>();
        }
    
        public int ArtistId { get; set; }
        public string Name { get; set; }
        public string UrlSafeName { get; set; }
    
        public virtual ICollection<Video> Videos { get; set; }
    }
}
