//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTAPI.Data.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Data.Entity.ModelConfiguration.Conventions;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            Database.SetInitializer<DatabaseEntities>(null);
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }
    
        public DbSet<Artist> Artists { get; set; }
        public DbSet<Video> Videos { get; set; }
    
        public virtual int CreateNewArtist(Nullable<int> artistId, string name, string urlSafeName)
        {
            var artistIdParameter = artistId.HasValue ?
                new ObjectParameter("ArtistId", artistId) :
                new ObjectParameter("ArtistId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var urlSafeNameParameter = urlSafeName != null ?
                new ObjectParameter("UrlSafeName", urlSafeName) :
                new ObjectParameter("UrlSafeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateNewArtist", artistIdParameter, nameParameter, urlSafeNameParameter);
        }
    
        public virtual int DeleteArtist(Nullable<int> artistId)
        {
            var artistIdParameter = artistId.HasValue ?
                new ObjectParameter("ArtistId", artistId) :
                new ObjectParameter("ArtistId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteArtist", artistIdParameter);
        }
    
        public virtual ObjectResult<GetArtists_Result> GetArtists(Nullable<int> artistId)
        {
            var artistIdParameter = artistId.HasValue ?
                new ObjectParameter("ArtistId", artistId) :
                new ObjectParameter("ArtistId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetArtists_Result>("GetArtists", artistIdParameter);
        }
    
        public virtual ObjectResult<GetVideos_Result> GetVideos(Nullable<int> videoId)
        {
            var videoIdParameter = videoId.HasValue ?
                new ObjectParameter("videoId", videoId) :
                new ObjectParameter("videoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetVideos_Result>("GetVideos", videoIdParameter);
        }
    
        public virtual int UpdateArtist(Nullable<int> artistId, string name, string urlSafeName)
        {
            var artistIdParameter = artistId.HasValue ?
                new ObjectParameter("ArtistId", artistId) :
                new ObjectParameter("ArtistId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var urlSafeNameParameter = urlSafeName != null ?
                new ObjectParameter("UrlSafeName", urlSafeName) :
                new ObjectParameter("UrlSafeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateArtist", artistIdParameter, nameParameter, urlSafeNameParameter);
        }
    }
}
