//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTAPI.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoId { get; set; }
        public string Isrc { get; set; }
        public string Title { get; set; }
        public string UrlSafeTitle { get; set; }
        public int ArtistId { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
